// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/user.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	SetDriverRating(ctx context.Context, in *SetDriverRatingRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	SetUserRating(ctx context.Context, in *SetUserRatingRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetTaxiForUser(ctx context.Context, in *GetTaxiForUserRequest, opts ...grpc.CallOption) (*GetTaxiForUserResponse, error)
	GetOrderForDriver(ctx context.Context, in *GetOrderForDriverRequest, opts ...grpc.CallOption) (*GetOrderForDriverResponse, error)
	GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) SetDriverRating(ctx context.Context, in *SetDriverRatingRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.OrderService/SetDriverRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) SetUserRating(ctx context.Context, in *SetUserRatingRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.OrderService/SetUserRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetTaxiForUser(ctx context.Context, in *GetTaxiForUserRequest, opts ...grpc.CallOption) (*GetTaxiForUserResponse, error) {
	out := new(GetTaxiForUserResponse)
	err := c.cc.Invoke(ctx, "/proto.OrderService/GetTaxiForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderForDriver(ctx context.Context, in *GetOrderForDriverRequest, opts ...grpc.CallOption) (*GetOrderForDriverResponse, error) {
	out := new(GetOrderForDriverResponse)
	err := c.cc.Invoke(ctx, "/proto.OrderService/GetOrderForDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderHistory(ctx context.Context, in *GetOrderHistoryRequest, opts ...grpc.CallOption) (*GetOrderHistoryResponse, error) {
	out := new(GetOrderHistoryResponse)
	err := c.cc.Invoke(ctx, "/proto.OrderService/GetOrderHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	SetDriverRating(context.Context, *SetDriverRatingRequest) (*EmptyResponse, error)
	SetUserRating(context.Context, *SetUserRatingRequest) (*EmptyResponse, error)
	GetTaxiForUser(context.Context, *GetTaxiForUserRequest) (*GetTaxiForUserResponse, error)
	GetOrderForDriver(context.Context, *GetOrderForDriverRequest) (*GetOrderForDriverResponse, error)
	GetOrderHistory(context.Context, *GetOrderHistoryRequest) (*GetOrderHistoryResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) SetDriverRating(context.Context, *SetDriverRatingRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDriverRating not implemented")
}
func (UnimplementedOrderServiceServer) SetUserRating(context.Context, *SetUserRatingRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserRating not implemented")
}
func (UnimplementedOrderServiceServer) GetTaxiForUser(context.Context, *GetTaxiForUserRequest) (*GetTaxiForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxiForUser not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderForDriver(context.Context, *GetOrderForDriverRequest) (*GetOrderForDriverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderForDriver not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderHistory(context.Context, *GetOrderHistoryRequest) (*GetOrderHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderHistory not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_SetDriverRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDriverRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SetDriverRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/SetDriverRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SetDriverRating(ctx, req.(*SetDriverRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_SetUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SetUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/SetUserRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SetUserRating(ctx, req.(*SetUserRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetTaxiForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxiForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetTaxiForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/GetTaxiForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetTaxiForUser(ctx, req.(*GetTaxiForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderForDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderForDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderForDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/GetOrderForDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderForDriver(ctx, req.(*GetOrderForDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/GetOrderHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderHistory(ctx, req.(*GetOrderHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDriverRating",
			Handler:    _OrderService_SetDriverRating_Handler,
		},
		{
			MethodName: "SetUserRating",
			Handler:    _OrderService_SetUserRating_Handler,
		},
		{
			MethodName: "GetTaxiForUser",
			Handler:    _OrderService_GetTaxiForUser_Handler,
		},
		{
			MethodName: "GetOrderForDriver",
			Handler:    _OrderService_GetOrderForDriver_Handler,
		},
		{
			MethodName: "GetOrderHistory",
			Handler:    _OrderService_GetOrderHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
